[package]
name = "finch-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.4.8"
color-eyre = "0.6.1"
serde = "1.0.136"
serde_derive = "1.0.136"
tera = "1.15.0"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tracing = "0.1.32"
tracing-subscriber = "0.3.9"
